FROM node:20.6.1-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
RUN npm run build

FROM nginx:stable-alpine as production-stage
RUN apt-get update && apt-get install -y curl
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK CMD curl -f http://localhost:80/ || exit 1
CMD ["nginx", "-g", "daemon off;"]
