FROM node:lts-alpine

RUN apk update && apk upgrade && apk add curl

RUN npm install -g http-server

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

USER node

RUN npm run build

EXPOSE 8080

HEALTHCHECK CMD curl -f http://localhost:8080/ || exit 1

CMD [ "http-server", "dist" ]
